### PR TITLE
Restructure docs, stage 2

### LINKED ISSUE #2805: Make the Getting Started section more intuitive
**Epics:**
#2051 – Restructuring Tarantool docs
#2052 – Integrate docs and trainings

# To do

Let's consolidate Getting Started pages in a unified Getting Started section. The audience of Getting Started is beginners who don't yet know much about Cartridge, app server functionality, etc. So it seems better to consolidate the Getting Started pages than to attach a separate Getting Started guide to every section.

# Feedback

1. @ igormunkin:
"Слушайте, а помните полгода назад еще был нормальный Getting Started без Cartridge: а он куда-то делся или я ослеп?"
"А вот тот, где там box.insert с группами был, его видимо уже не найти?"
"Нашёл! Но было сложно."
https://www.tarantool.io/en/doc/latest/getting_started/getting_started_db/#creating-db-locally

2. This page (Pokemon Go guide) is apart from the other Getting Started pages:
https://www.tarantool.io/en/doc/latest/book/app_server/creating_app/

3. See this discussion: https://github.com/tarantool/doc/discussions/2810

### LINKED ISSUE #2987: Add the umbrella section Concepts
**New structure mind map:** https://miro.com/app/board/uXjVO-EJIyE=/
**Plan of the grand restructuring:** https://www.notion.so/tarantool/Tarantool-CE-c075d0db9ce24893beca704c145ae501

**Product:** Tarantool
**Audience/target:** analysts, product managers
**Epic:** [Restructuring Tarantool docs](https://github.com/tarantool/doc/issues/2051)
**SME:** @ NeraverinTarantool

# Details

This is an **epic** estimated at 29sp. But it should be done in a single PR. So let's perceive it as a single (but huge) task.
Details and decomposition can be found in the PR: https://github.com/tarantool/doc/pull/3116.

Plan: https://www.notion.so/tarantool/Tarantool-CE-c075d0db9ce24893beca704c145ae501#a89e84e55afe45f091df87be9a32a884

Resolving this issue will also resolve https://github.com/tarantool/doc/issues/2805

### PR DESCRIPTION
**Pull request by patiencedaur**
Resolves #2987 
Resolves https://github.com/tarantool/doc/issues/2805

**Rebase this often!**

Plan:
https://www.notion.so/tarantool/Tarantool-CE-c075d0db9ce24893beca704c145ae501#a89e84e55afe45f091df87be9a32a884
(internal document)

- [x] Move Access control to Administration (1sp)
- [x] Create new Concepts section
- [x] Application server -> Concepts, How-to, other sections (5sp)
- [x] Data model -> Concepts, How-to, Reference (5sp)
- [x] Indexes -> Concepts, How-to (3sp)
- [x] Sharding -> Concepts, Administration, Reference, How-to (5sp)
- [x] Replication -> Concepts, other sections (5sp)
- [x] Fill the new Concepts section with all the necessary info (audience: product teams, analysts) (1sp)
        
        - Application server
        - Data model
        - Transactions
        - Sharding
        - Replication
        - Binary protocol: top-level page with a link to https://www.tarantool.io/en/doc/latest/dev_guide/internals/box_protocol/
        - Storage engines
        
- [x] Replace links where needed (1sp)
- [x] Add links to Overview (1sp)
- [x] Transfer translations (1sp)
- [x] Add redirects (1sp): https://github.com/tarantool/tarantool.io/pull/1296

### CODE REVIEW

**Comment by patiencedaur** [comment]
### Redirects

- https://github.com/tarantool/tarantool.io/pull/1296

**App server**

- [x] - /book/box/authentication -> /book/admin/access_control
- [x] - /book/app_server/launching_app -> /how-to/app/launching_app
- [x] - /book/app_server/creating_app -> /how-to/app/creating_app
- [x] - /book/app_server/cookbook -> /how-to/app/cookbook
- [x] - /book/app_server/using_ide -> /how-to/app/using_ide
- [x] - /book/app_server/installing_module -> /book/admin/modules
- [x] - /book/app_server/reloading_module -> /book/admin/modules
- [x] - /book/app_server/contributing_module -> /dev_guide/contributing_module
- [x] - /book/app_server/luajit_memprof -> /reference/tooling/luajit_memprof
- [x] - /book/app_server/luajit_getmetrics -> /reference/tooling/luajit_getmetrics

**Tooling**

- [x] - /reference/tarantoolctl -> /reference/tooling/tarantoolctl
- [x] - /reference/tt_cli/* -> /reference/tooling/tt_cli/*
- [x] - /reference/interactive_console -> /reference/tooling/interactive_console

**Data model**

- [x] - /book/box/data_model/ -> /concepts/data_model

**Indexes**

- [x]  /book/box/indexes -> /concepts/data_model/indexes

**Sharding**

- [x] /reference/reference_rock/vshard/vshard_quick/ -> /how-to/vshard_quick
- [x] - /reference/reference_rock/vshard/vshard_admin/ -> /book/admin/vshard_admin/

**Triggers**

- [x] - /book/box/triggers/ -> /concepts/triggers

**Transactions**

- [x] - /book/box/atomic -> /concepts/atomic

**Storage engines**

- [x] - /book/box/engines/* -> /concepts/engines/*

**Replication**

- [x] - /book/replication/index -> /concepts/replication/index
- [x] - /book/replication/repl_architecture/ -> /concepts/replication/repl_architecture/
- [x] - /book/replication/repl_sync/ -> /concepts/replication/repl_sync/
- [x] - /book/replication/repl_leader_elect/ -> /concepts/replication/repl_leader_elect/
- [x] - /book/replication/repl_bootstrap/ -> /how-to/replication/repl_bootstrap/
- [x] - /book/replication/repl_add_instances/ -> /how-to/replication/repl_add_instances/
- [x] - /book/replication/repl_remove_instances/ -> /how-to/replication/repl_remove_instances/
- [x] - /book/replication/repl_monitoring/ -> /book/admin/replication/repl_monitoring/
- [x] - /book/replication/repl_recover/ -> /book/admin/replication/repl_recover/
- [x] - /book/replication/repl_reseed/ -> /book/admin/replication/repl_reseed/
- [x] - /book/replication/repl_problem_solving/ -> /book/admin/replication/repl_problem_solving/

**Comment by patiencedaur** [comment]
Fix warnings: (this comment will be deleted once all the warnings are fixed)

/doc/doc/book/intro.rst:22: WARNING: undefined label: app_server
/doc/doc/getting_started/connecting_to_cluster.rst:65: WARNING: unknown document: /getting_started/getting_started_cxx
/doc/doc/getting_started/writing_cluster_code.rst:15: WARNING: unknown document: /getting_started/getting_started_cartridge
doc/how-to/using_docker.rst:57: WARNING: undefined label: app_server
/doc/doc/book/monitoring/grafana_dashboard.rst:19: WARNING: undefined label: tarantool-metrics
/doc/doc/book/monitoring/grafana_dashboard.rst:71: WARNING: undefined label: cartridge-role
/doc/doc/book/monitoring/grafana_dashboard.rst:71: WARNING: undefined label: prometheus
/doc/doc/book/monitoring/grafana_dashboard.rst:91: WARNING: undefined label: cartridge-role
/doc/doc/book/monitoring/grafana_dashboard.rst:91: WARNING: undefined label: json
/doc/doc/book/connectors/cxx/tntcxx_api.rst:9: WARNING: unknown document: /getting_started/getting_started_cxx
doc/book/connectors/__c.rst:158: WARNING: Unparseable C cross-reference: 'tarantoolc:tnt_object_format'
Invalid C declaration: Expected end of definition. [error at 10]
  tarantoolc:tnt_object_format
  ----------^
doc/book/connectors/__c.rst:201: WARNING: Unparseable C cross-reference: 'tarantoolc:tnt_connect'
Invalid C declaration: Expected end of definition. [error at 10]
  tarantoolc:tnt_connect
  ----------^
/doc/doc/reference/configuration/index.rst:315: WARNING: unknown document: /reference/tarantoolctl
/doc/doc/reference/reference_lua/box_index/stat.rst:30: WARNING: undefined label: box_introspection-box_stat_vinyl_details
/doc/doc/reference/reference_lua/datetime/new.rst:16: WARNING: unknown document: ./datetime/datetime_object
/doc/doc/reference/reference_lua/datetime/datetime_object.rst:252: WARNING: undefined label: interval-new
/doc/doc/reference/reference_lua/datetime/datetime_object.rst:343: WARNING: undefined label: interval-new
/doc/doc/release/major-features.rst:68: WARNING: unknown document: /book/app_server/luajit_memprof
/doc/doc/release/2.7.1.rst:20: WARNING: unknown document: /book/app_server/luajit_memprof
/doc/doc/release/2.7.1.rst:65: WARNING: unknown document: /book/app_server/luajit_memprof
/doc/doc/contributing/docs/markup/admonitions.rst:47: WARNING: unknown document: /getting_started/getting_started_go
done
writing... /doc/doc/how-to/sql/sql_tutorial.rst:50: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.
/doc/doc/how-to/sql/sql_tutorial.rst:698: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.
/doc/doc/how-to/sql/sql_tutorial.rst:705: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.
/doc/doc/how-to/sql/sql_tutorial.rst:799: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.
/doc/doc/concepts/coop_multitasking.rst:183: WARNING: Pygments lexer name 'memtx' is not known
/doc/doc/book/box/atomic/txn_mode_default.rst:22: WARNING: Pygments lexer name 'enabling' is not known
/doc/doc/reference/reference_lua/box_tuple/field_path.rst:36: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.
/doc/doc/release/1.8.rst:39: WARNING: Could not lex literal_block as "tarantoolsession". Highlighting skipped.

**Comment by p7nov** [comment]
That's an impressive work!
I've looked through changes and checked that nothing is lost and the deployment looks OK in general. Didn't check the new text thoroughly.

However, I've got one concern about repeating headings in different top-level sections. We have **Replication** and **Sharding** in **How-to**, in **Concepts**, and in **Administration**. This already affects the search: when you type "sharding", you get three results with the same heading. This may be confusing. Moreover, I'm not sure how this will affect SEO. Perhaps we can think of more specific headings.

**Review by p7nov — APPROVED** [review]
LGTM

**Comment by patiencedaur** [comment]
For some reason the `:fullwidth:` directive cannot remove the headers in the right menu. After this PR is merged, we need to check with the frontend developers:
- https://github.com/tarantool/tarantool.io/issues/1297

**Review by xuniq — APPROVED** [review]

**Pull request merged**
