### PR TITLE
Fixes gh-799 box.space._vcollation

### PR DESCRIPTION
**Pull request by pgulutzan**
There was a commit for issue#799 https://github.com/tarantool/doc/issues/799 in 2019
https://github.com/tarantool/doc/commit/80bcbd3dd83d3d53b45dedfd8c9cea2b27c4ebdd
but, as can be seen from the comments on issue#799, for some reason it disappeared.
So this does again what was in that commit,, but there are a few differences.
() Sometime between 2019 and 2021, somebody put some of the _v* (sysviews) descriptions
in separate files. This is not really necessary now because redundancy was removed,
but I didn't remove the files.
() There was description in _priv re how privileges work etc. I replaced it with
"See Access control for details about user privileges."

One of the people involved with the 2019 correspondence was @Totktonada.

### CODE REVIEW

**Comment by patiencedaur** [comment]
Crowdin link for translation: https://crowdin.com/project/tarantool-docs/ru#/pgulutzan-gh-799/en/reference/reference_lua

**Comment by patiencedaur** [comment]
@Totktonada 
We found that the term "system view" is not quite clear. It is a read-only copy of a system space, which has limited user permissions, correct? If so, we suggest renaming it to "system space view". "System view" can be read as "view of the system" or "view used by the system", while it is really a "view of a system space". What do you think?
In Russian, "system space" and "system space view" will be termed системный спейс and представление системного спейса, accordingly.

**Comment by Totktonada** [comment]
Both 'system view' and 'system space view' sound ok for me. Technically the latter is more precise. I don't mind. However 'system views' terminology was introduced together with the feature: https://github.com/tarantool/tarantool/commit/4c15968178be0d0ade2517c54f0fb56e4973116d. I don't know, whether it worth to change it. Can we ask @locker as well?

> It is a read-only copy of a system space, which has limited user permissions, correct?

More or less, but it is a bit inaccurate description. We can say that a view is an object, which works like the original space, but with a set of automatically applied filters. If it would be a copy, its data would not be updated at updating of the original space. The idea of our views is very similar to [views in SQL](https://www.geeksforgeeks.org/sql-views/).

**Comment by patiencedaur** [comment]
Thank you! There are only 4 matches for "system view" in the current doc. So if @locker approves and we decide to fix the English term, I expect it to be easy and relatively quick.

**Comment by locker** [comment]
> Both 'system view' and 'system space view' sound ok for me. Technically the latter is more precise. I don't mind. However 'system views' terminology was introduced together with the feature: [tarantool/tarantool@4c15968](https://github.com/tarantool/tarantool/commit/4c15968178be0d0ade2517c54f0fb56e4973116d). I don't know, whether it worth to change it. Can we ask @locker as well?

@Totktonada @patiencedaur I'm fine either way. If there are just a few occurrences in the doc, I think it wouldn't hurt to update them.

**Pull request merged**
