### PR TITLE
Update go-connector (decimal and datetime)

### PR DESCRIPTION
**Pull request by ligurio**
Follows up https://github.com/tarantool/go-tarantool/issues/96
Follows up https://github.com/tarantool/go-tarantool/issues/118

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
LGTM (but should wait for the linked issues).

**Comment by ligurio** [comment]
@patiencedaur can we proceed and merge it?

**Comment by ligurio** [comment]
@oleg-jukovec FYI

**Comment by patiencedaur** [comment]
> @patiencedaur can we proceed and merge it?

Sure. Merging it.

**Pull request merged**
